### ISSUE TITLE
A few 'time out' fields are not populated

### ISSUE THREAD

**Issue by AlinaKisialiova** [marc-ed-raffalli/fill-my-timesheet#2]
Hi @marc-ed-raffalli ,

Thank you for the plugin!

When I run it, there are a few 'time out' gaps in my timesheets.

**Timesheets**
![image](https://user-images.githubusercontent.com/11226142/79849357-426fcb80-83ba-11ea-8d7f-1ddc6b400690.png)
![image](https://user-images.githubusercontent.com/11226142/79849376-48fe4300-83ba-11ea-85e4-9f398672d499.png)

**Console log**
![image](https://user-images.githubusercontent.com/11226142/79849433-5ddad680-83ba-11ea-839f-b028befb6201.png)

**My report**
![image](https://user-images.githubusercontent.com/11226142/79849520-7f3bc280-83ba-11ea-85d4-fa54307c2526.png)

**Comment by marc-ed-raffalli** [comment]
Hi @AlinaKisialiova , sorry I only saw your message today.
The script is quite unstable on the purely HR page, partially due to the page's internal implementation.
A way to work around the issue is to run a report with the time only and one with the comment.

**Comment by AlinaKisialiova** [comment]
Got it.
Thanks, @marc-ed-raffalli !
